---
root: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - jest

env:
  node: true
  jest: true
  browser: true
  es2021: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: 0
